#!/bin/sh
grunt build
version=`cat VERSION`
sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" app/private/quartz-rails/lib/vhx/quartz/version.rb
sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" bower.json
sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" package.json
cd app/private/quartz-rails
rake build
git add .
git commit -m "bump version to $version"
git push origin master
rake release
cd ../../../
git add .
git commit -m "bump version to $version"
git push origin master
git tag -a v$version -m "Release version $version"
git push origin master --tags
