#!/bin/sh
echo "Hold up. Have you updated the VERSION file? [y]es or [n]o"
read type

if [ "$type" == "y" ]; then
  grunt build
  version=`cat VERSION`
  sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" app/private/quartz-rails/lib/vhx/quartz/version.rb
  sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" bower.json
  sed -i '' "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]*/$version/" package.json
  cd quartz-rails
  rake build
  git add .
  git commit -m "bump version to $version"
  git push origin master
  rake release
  cd ../
  git add .
  git commit -m "bump version to $version"
  git push origin master
  git tag -a v$version -m "Release version $version"
  git push origin master --tags
else
  echo "Crisis averted. Update it then come on back."
fi
