#!/bin/sh
grunt build
version=`cat VERSION`
sed -i.bak "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]/$version/" app/private/quartz-rails/lib/vhx/quartz/version.rb
sed -i.bak "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]/$version/" bower.json
sed -i.bak "1,/[0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]/$version/" package.json
rm app/private/quartz-rails/lib/vhx/quartz/version.rb.bak
rm bower.json.bak
rm package.json.bak
cd app/private/quartz-rails
rake build
git commit -am "bump version to $version"
git push origin master
rake release
cd ../../../
git commit -am "bump version to $version"
git push origin master
git tag -a $version -m "Release version $version"
git push origin master --tags
