#!/bin/sh
echo "Hold up. Have you updated the VERSION and the CHANGELOG file? [y]es or [n]o"
read type

if [ "$type" == "y" ]; then

  echo "Do you have permission to publish to the NPM Quartz Package? [y] or [n]o"
  read type

  if [ "$type" == "y" ]; then
    grunt build
    version=`cat VERSION`
    sed -i '' "1,/[0-9]*\.[0-9]*\.[0-9]*/s/[0-9]*\.[0-9]*\.[0-9]*/$version/" package.json
    git add .
    git commit -m "bump version to $version"
    git push origin master
    git tag -a v$version -m "Release version $version"
    git push origin master --tags
    npm publish
  else
    echo "Ask dave@vhx.tv or scott@vhx.tv for access."
  fi
else
  echo "Crisis averted. Update it then come on back."
fi
